version: "3.9"
services:
  dockerignore-dev:
    image: dockerignore-dev
    build:
        context: .
        dockerfile: Dockerfile.dev
    container_name: dockerignore-dev
    volumes:
      - ./main.go:/app/main.go
    env_file:
      - .env
    ports:
      - 8080:8080