version: "3.9"
services:
  dockerignore-test:
    image: dockerignore-test
    build:
        context: .
        dockerfile: Dockerfile.test
    container_name: dockerignore-test
    volumes:
      - ./main_test.go:/app/main_test.go
    env_file:
      - .env
    ports:
      - 8080:8080
    command: go test